
openapi: 3.0.0
info:
  title: Rumorz SDK API
  version: 1.0.0
servers:
  - url: https://rumorz.azurewebsites.net/v0
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
security:
  - ApiKeyAuth: []
paths:
  /graph/get_feed:
    post:
      tags:
        - Graph
      summary: get_feed
      description: Get the feed of posts related to the specified entities and filters.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                lookback:
                  type: string
                  enum: [1H, 6H, 12H, 1D, 7D, 30D, 90D]
                  description: Time period to look back
                sentiment_gte:
                  type: number
                sentiment_lte:
                  type: number
                page:
                  type: integer
                limit:
                  type: integer
            example:
              ids: [115176]
              lookback: 7D
              sentiment_gte: 0.5
              sentiment_lte: 1.0
              page: 1
              limit: 10
      responses:
        '200':
          description: Success
  /graph/search_entities:
    post:
      tags:
        - Graph
      summary: search_entities
      description: Search for entities in the Rumorz Graph by name and/or symbol.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name_search:
                  type: string
                symbol_search:
                  type: string
                asset_class:
                  type: string
                  enum: [crypto, commodities]
                entity_type:
                  type: string
                  enum: [financial_asset, company, organization, person, place]
                limit:
                  type: integer
            example:
              name_search: "Bitcoin"
              symbol_search: "BTC"
              asset_class: "crypto"
              entity_type: "financial_asset"
              limit: 1
      responses:
        '200':
          description: Success
  /graph/get_ranking:
    post:
      tags:
        - Graph
      summary: get_ranking
      description: Returns a ranking of every single entity in the Graph based on the given parameters.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lookback:
                  type: string
                  enum: [1H, 6H, 12H, 1D, 7D, 30D, 90D]
                entity_type:
                  type: string
                  enum: [financial_asset, company, organization, person, place]
                sort_by:
                  type: string
                  enum: [mentions, sentiment, excitement, optimism, pessimism, fear, uncertainty, surprise]
                ascending:
                  type: boolean
                page:
                  type: integer
                limit:
                  type: integer
            example:
              lookback: 1D
              entity_type: "financial_asset"
              sort_by: "mentions"
              ascending: false
              page: 1
              limit: 10
      responses:
        '200':
          description: Success
  /graph/get_metrics:
    post:
      tags:
        - Graph
      summary: get_metrics
      description: Get metrics for an entity in the Rumorz Graph.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                metrics:
                  type: array
                  items:
                    type: string
                  enum: [mentions, sentiment, excitement, optimism, pessimism, fear, uncertainty, surprise, price]
                lookback:
                  type: string
                  enum: [1H, 6H, 12H, 1D, 7D, 30D, 90D]
                page:
                  type: integer
                limit:
                  type: integer
            example:
              ids: [115176]
              metrics: ["sentiment"]
              lookback: 1D
              page: 1
              limit: 100
      responses:
        '200':
          description: Success
  /graph/get_price_stats:
    post:
      tags:
        - Graph
      summary: get_price_stats
      description: Get summary price stats of a financial asset entity in the Rumorz Graph.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
            example:
              id: 115176
      responses:
        '200':
          description: Success
  /agent/summarize:
    post:
      tags:
        - Agent
      summary: summarize
      description: Summarize events and news for any entity in the graph.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                timestamp:
                  type: string
                  format: date-time
                sentiment_gte:
                  type: number
                sentiment_lte:
                  type: number
            example:
              id: 115176
              timestamp: "2023-10-01T00:00:00Z"
              sentiment_gte: 0.5
              sentiment_lte: 1.0
      responses:
        '200':
          description: Success