openapi: 3.0.0
info:
  title: Rumorz API
  description: API documentation for Rumorz endpoints
  version: 1.0.0
servers:
  - url: http://rumorz-api.eastus2.azurecontainer.io
paths:
  /graph/get_feed:
    post:
      summary: get_feed
      description: Get the feed of posts related to the specified entities and filters.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                lookback:
                  type: string
                scores_filter:
                  type: string
                page:
                  type: integer
                limit:
                  type: integer
      responses:
        '200':
          description: Success
  /graph/search_entities:
    post:
      summary: search_entities
      description: Search for entities in the Rumorz Graph by name and/or symbol.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                asset_class:
                  type: string
                entity_type:
                  type: string
                symbol_search:
                  type: string
                limit:
                  type: integer
      responses:
        '200':
          description: Success
  /graph/get_ranking:
    post:
      summary: get_ranking
      description: Returns a ranking of every single entity in the Graph based on the given parameters.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lookback:
                  type: string
                page:
                  type: integer
                limit:
                  type: integer
                sort_by:
                  type: string
                entity_type:
                  type: string
                scores_filter:
                  type: string
                ascending:
                  type: boolean
      responses:
        '200':
          description: Success
  /graph/get_metrics:
    post:
      summary: get_metrics
      description: Get metrics for an entity in the Rumorz Graph.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                operation:
                  type: string
                metrics:
                  type: array
                  items:
                    type: string
                lookback:
                  type: string
                page:
                  type: integer
                limit:
                  type: integer
      responses:
        '200':
          description: Success
  /agent/create_agent:
    post:
      summary: create_agent
      description: Create an agent with a goal, name, and personality.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                goal:
                  type: string
                name:
                  type: string
                personality:
                  type: string
      responses:
        '200':
          description: Success
  /agent/summarize:
    post:
      summary: summarize
      description: Summarize events and news for any entity in the graph.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                timestamp:
                  type: string
                scores_filter:
                  type: string
      responses:
        '200':
          description: Success
  /agent/get_state:
    post:
      summary: get_state
      description: Get the state of an agent, including current sentiment, personality, trading strategy, and more.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
      responses:
        '200':
          description: Success
  /agent/get_logs:
    post:
      summary: get_logs
      description: Get the logs of an agent.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                lookback:
                  type: string
                limit:
                  type: integer
      responses:
        '200':
          description: Success